name: edu_app
description: "Educational app"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0-209.1.beta


dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  dartx: ^1.2.0
  intl: ^0.19.0
  uuid: ^4.5.1
  go_router: ^14.8.0
  google_fonts: ^6.2.1
  flutter_dotenv: ^5.2.1
  flutter_markdown: ^0.7.6+2

  table_calendar: ^3.1.3
  flutter_deck: ^0.18.0
  flutter_ai_toolkit: ^0.6.8

  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  firebase_ui_auth: ^1.16.1
  cloud_firestore: ^5.6.5
  firebase_vertexai: ^1.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
