name: edu_app
description: "Educational app"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0-209.1.beta


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  table_calendar: ^3.1.3
  firebase_core: ^3.12.1
  firebase_vertexai: ^1.4.0
  flutter_ai_toolkit: ^0.6.8
  google_fonts: ^6.2.1
  flutter_markdown: ^0.7.6+2
  firebase_auth: ^5.5.1
  google_sign_in: ^6.2.2
  firebase_ui_auth: ^1.16.1
  go_router: ^14.8.0
  cloud_firestore: ^5.6.5
  dartx: ^1.2.0
  flutter_dotenv: ^5.2.1
  uuid: ^4.5.1
  intl: ^0.19.0
  flutter_deck: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:
  assets:
    - .env
